title: Ninja Turdle
email: mrturdle@ninjaturdle.com
description: A shitty adventure.
base_url: http://ninjaturdle.com
deploy: call deploy_ninjaturdle # rsync via alias manager
template_engine: handlebars
posts:
    directory: posts
    template: post.hbs
pages:
    - index.hbs
    - download.hbs
    - story.hbs
directories:
    - assets
