title: Ninja Turdle
email: mrturdle@ninjaturdle.com
description: A shitty adventure.
base_url: http://ninjaturdle.com
deploy: call deploy_ninjaturdle # rsync via alias manager
date_format: MMMM d, yyyy
template_engine: handlebars
posts:
    directory: posts
    template: post.hbs
pages:
    - index.hbs
    - music.hbs
    - story.hbs
    - tags.hbs
directories:
    - name: assets
